GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Jingle Bells the novel",
  "author": "Miranda Frogsgrove",
  "url": "http://google.com/novel",
  "likes": 3453234
}